### ISSUE TITLE
[PROPOSAL] Web Socket Protocol

### ISSUE THREAD

**Issue by youen** [CGI-FR/LINO#110]
### CommandMessage:

- `id` : `string`  identifiant unique du message
- `action` : `string`  valeurs possible : "ping", "extract_tables", "extract_relations", "pull_open", "push_open", "push_data", "push_commit", "push_close"
- `payload` : `Payload` payload différent en fonction du type de l'action

### ResultMessage:

- `id` : `string` identifiant du message d'origine
-  error : `Error|null`
-  next : `bool` retourne `true` si il y a d'autres messages à suivre
- `payload` : `Payload`

### PullOpenPayloay

- table :  `string` : nom de la table
- colums: `[]string` : liste des colonnes
- filtre : Filtre

#### `Filter` 

- limit     `number`
- values   `map[string]JSONValue`
- where  `string`
- distinct `bool`

## PingPayload

**Comment by adrienaury** [comment]
Il manque les actions 

- truncate
- enable_constraints
- disable_constraints

**Comment by youen** [comment]
C'est un mode d'ouverture.

De mon point de vue c'est mieux de désactiver les contraintes au plus proche de la base pour pouvoir les réactiver en cas d'erreur pendant le push.

**Comment by EricSimon** [comment]
Ajout de "schema" dans PullOpenPayloay
