### ISSUE TITLE
[BUG] Special character in password leads to error

### ISSUE THREAD

**Issue by CapKicklee** [CGI-FR/LINO#179]
Hi,

A user could not connect to an Oracle Database after using a `lino dc add` command, with a password containing a #.
Could it be possible that the yaml file resulting from the command is interpreting it as a comment?

Is there any fix or alternative way of using it?

Thanks,

**Comment by adrienaury** [comment]
Could you give more details 

- copy/paste of the error
- content of the YAML file (replace the password with a fake one)
- when is the error occuring ? (lino dc add ? or lino pull ? ) => the complete command

**Comment by CapKicklee** [comment]
Sorry for the late update, we could not get to know really what password they were using (only special character was a '#'). Error was an Oracle one, specifying user logon informations were wrong.

Users changed the password as a counter-measure, so no more updates on the topic, I'll close the issue
