### ISSUE TITLE
[BUG] Postgres : error 'no table named ListX' for command ' lino id create "ListX" '

### ISSUE THREAD

**Issue by fr4nckdijoux** [CGI-FR/LINO#243]
### **Initial condition:**
Windows Computer
Postgresql db with table ListX (table name include UPPER CASE character and no foreign keys)
lino dataconnector add DB_prod --read-only --password postgresql://postgres@localhost:5432/DB_prod?sslmode=disable
lino relation extract DB_prod
lino table extract DB_prod

### **Action**
lino id create "ListX"

### **Problem**
no table named ListX
whereas in file tables.yml, the table ListX is correctly displayed

### **Expected** 
Whatever the case of table name, the lino command should work.

NB: After call With @adrienaury 
1/2: In case of no relation for request "lino id create "ListX", the feedback shoud propose to execute the command "lino pull --table "listx" DB_prod "
2/2  for request "lino pull --table "listx" DB_prod | jq" the reply is "3:07PM FTL Fatal error stop the pull command error="pq: la relation « listx » n'existe pas" action=pull" => investigation must be done on this error.

### **Additional info**
extract from tables.yml
  - name: ListX
    keys:
      - id

**Comment by youen** [comment]
Thank you for your feedback. I confirm that it is indeed a bug; we should protect the table names with double quotes in this [section](https://github.com/CGI-FR/LINO/blob/bf106f81186f574b22f35c2e6e75ebd2284c81a4/internal/infra/pull/sql_datasource.go#L143). However, this code is common with other SQL database engines. I'm not sure if there will be any consequences for users of Oracle, SQL Server, or MariaDB.

**Comment by adrienaury** [comment]
@fr4nckdijoux this will be fixed in the next version of LINO v3.0.0

**Comment by adrienaury** [comment]
Hello @fr4nckdijoux 
This is fixed in LINO v3.0.0
