### ISSUE TITLE
[Request] upgrade sijms/go-ora in 2.8.19 due to ORA-01483 errors

### ISSUE THREAD

**Issue by pbq** [CGI-FR/LINO#300]
Hi folks,
 
is it possible to upgrade sijms/go-ora to the latest version 2.8.19. 

Some of our users are experiencing "ORA-01483 : invalid length for DATE or NUMBER bind variable" errors in similar use cases than in issue https://github.com/sijms/go-ora/issues/557.

Thanks

**Comment by pbq** [comment]
issue 300 ! 🎉

**Comment by adrienaury** [comment]
@pbq j'ai publié la version https://github.com/CGI-FR/LINO/releases/tag/v3.0.2-beta1 en beta, peux tu tester et me dire si c'est ok

**Comment by pbq** [comment]
salut @adrienaury , merci pour la prise en compte. 
je te fais un retour dès que possible.

**Comment by pbq** [comment]
salut @adrienaury, pour info, l'équipe a pu tester la nouvelle version beta. Plus d'erreurs ORA-01483.

**Comment by adrienaury** [comment]
@pbq  parfait je vais publier une version corrective, j'embarque aussi d'autres montées de version par la même occasion.
