### ISSUE TITLE
MariaDB support

### ISSUE THREAD

**Issue by RastaChaum** [CGI-FR/LINO#7]
Hello,

We tried yours tools, but we've been quickly stopped by this problem.
when executing "lino relation extract source" we got "no extractor found for database type"
While reading doc, we found that LINO doesn't support MariaDB or/and MySQL.
How to add this support ?

**How to Reproduct**
run `docker run -v /home/vagrant/LINO/LINO:/home/lino lino_lino dataconnector add source mysql://<ip>:<port>?sslmode=disable -U USER -P PASS -s myschema`

run `docker run --env PASS=password --env USER=user -v /home/vagrant/LINO/LINO:/home/lino lino_lino table extract source`

**Comment by adrienaury** [comment]
Hi,

Thanks for trying !

To add MariaDB/MySQL support, a few files needs to be added to the repository 

- [ ] internal/infra/relation/extractor_mariadb.go : it need to implement a single function `func (d PostgresDialect) SQL(schema string) string ` that will just return the sql query to fetch all the relations in the named schema, use the other files like extractor_postgres.go as an example
- [ ] internal/infra/table/extractor_mariadb.go : same, but it return the sql query to fetch all the tables in the named schema, use the other files like extractor_postgres.go as an example
- [ ] internal/infra/push/datadestination_mariadb.go : it needs to implement the SQLDialect interface (defined in internal/infra/pull/sql_datasource.go) that gives some specifics about the SQL dialect (like how do you create an UPDATE statement), use the other files like datadestination_postgres.go as an example
- [ ] internal/infra/pull/datasource_mariadb.go : same as above and pretty straightforward

If you are OK to give a try, please submit a PR i will gladly take the time to review and merge it to the base code ! You have your database already up to test and make sure it's working it seems :)
